config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :players
  resources :teams

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/player.rb
class Player < ApplicationRecord
  validates :playerName, presence: true, :uniqueness => {:case_sensitive => false}

  
end

app/models/team.rb
class Team < ApplicationRecord
  validates :teamName, presence: true, :uniqueness => {:case_sensitive => false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:playerName, :teamName, :dpi, :winSens, :gameSens, :zoomSens, :resolution, :aspectRatio, :monitor, :mouse, :keyboard, :mousePad, :headset)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    filler_array = []
    @players = Player.all

    #only show players that belongs to team
    @players.each do |p|
      if p.teamName == @team.teamName
        filler_array.push(p)
      end
    end
    @players = filler_array
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:teamName)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

    #teams
    @astralis = Team.find_by teamName: 'Astralis';
    @virtusPro = Team.find_by teamName: 'Virtus Pro';
    @sk = Team.find_by teamName: 'SK Gaming';
    @natusVincere = Team.find_by teamName: 'Natus Vincere';
    @fnatic = Team.find_by teamName: 'Fnatic';
    @nip = Team.find_by teamName: 'Ninjas In Pyjamas';
    @faze = Team.find_by teamName: 'Faze Clan';
    @c9 = Team.find_by teamName: 'Cloud 9';
    @g2 = Team.find_by teamName: 'G2 Esports';

    #player
    @coldzera = Player.find_by playerName: 'Coldzera';
    @fallen = Player.find_by playerName: 'Fallen';
    @device = Player.find_by playerName: 'Dev1ce';
    @simple = Player.find_by playerName: 'S1mple';
    @snax = Player.find_by playerName: 'Snax';
    @shox = Player.find_by playerName: 'Shox';
    @forest = Player.find_by playerName: 'F0rest';
    @olofmeister = Player.find_by playerName: 'Olofmeister';
    @scream = Player.find_by playerName: 'Scream';
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Csgo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playerName %>
    <%= f.text_field :playerName %>
  </div>

  <div class="field">
    <%= f.label :teamName %>
    <%= f.text_field :teamName %>
  </div>

  <div class="field">
    <%= f.label :dpi %>
    <%= f.number_field :dpi %>
  </div>

  <div class="field">
    <%= f.label :winSens %>
    <%= f.number_field :winSens %>
  </div>

  <div class="field">
    <%= f.label :gameSens %>
    <%= f.text_field :gameSens %>
  </div>

  <div class="field">
    <%= f.label :zoomSens %>
    <%= f.text_field :zoomSens %>
  </div>

  <div class="field">
    <%= f.label :resolution %>
    <%= f.text_field :resolution %>
  </div>

  <div class="field">
    <%= f.label :aspectRatio %>
    <%= f.text_field :aspectRatio %>
  </div>

  <div class="field">
    <%= f.label :monitor %>
    <%= f.text_field :monitor %>
  </div>

  <div class="field">
    <%= f.label :mouse %>
    <%= f.text_field :mouse %>
  </div>

  <div class="field">
    <%= f.label :keyboard %>
    <%= f.text_field :keyboard %>
  </div>

  <div class="field">
    <%= f.label :mousePad %>
    <%= f.text_field :mousePad %>
  </div>

  <div class="field">
    <%= f.label :headset %>
    <%= f.text_field :headset %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<head>
  <title>CSGO TEAMS</title>

  <!-- Custom Fonts -->
  <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">

</head>

<body>

  <!-- NavBar -->
  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-left">
                <li>
                    <%= link_to "CSGOCONFIG", welcome_index_path%>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <%= link_to "Home", welcome_index_path%>
                  </li>
                  <li>
                      <%= link_to "Teams", teams_path%>
                  </li>
                  <li>
                      <%= link_to "Players", players_path%>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>

  <!-- Players -->
  <section class="bg-dark" id="about">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">CSGO PLAYERS</h2>
                <tbody>
                  <% @players.order(:playerName).each do |player| %>
                    <tr>
                      <br></br>
                      <td><%= link_to player.playerName, player %></td>
                      <!-- <td><%=player.teamName%></td> -->
                      <br></br>
                      <!-- <td><%= player.teamName %></td> -->

                      <!-- <td><%= link_to 'Show', player %></td> -->
                      <!-- <td><%= link_to 'Edit', edit_player_path(player) %></td> -->
                      <!-- <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                    </tr>
                  <% end %>
                </tbody>
              </div>
          </div>
      </div>
  </section>

</body>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<head>
  <title><%=@player.playerName%></title>

  <!-- Custom Fonts -->
  <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">

</head>

<body>

  <!-- NavBar -->
  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-left">
                <li>
                    <%= link_to "CSGOCONFIG", welcome_index_path%>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <%= link_to "Home", welcome_index_path%>
                  </li>
                  <li>
                      <%= link_to "Teams", teams_path%>
                  </li>
                  <li>
                      <%= link_to "Players", players_path%>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>

  <!-- Search -->
  <section class="bg-dark" id="about">
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 text-center">
                  <h2 class="section-heading"><%=@player.playerName%></h2>
                  <hr class="light">
                  <h4 class="section-heading">Top Teams. Top Pros. Hand-picked by CSGOCONFIG.</h4>
                  <br></br>
                  <a href="#services" class="page-scroll btn-round-lg btn-xl">Explore Now</a>
              </div>
          </div>
      </div>
  </section>

  <!-- Page Content -->
  <div class="container" id="services">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <%=@player.teamName%> | <%=@player.playerName%>
            </h1>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i> Mouse Settings</h4>
                </div>
                <div class="panel-body">
                  <p>Game Sensitivity: <%=@player.gameSens%></p>
                  <p>Zoom Sensitivity: <%=@player.zoomSens%></p>
                  <p>Mouse DPI: <%=@player.dpi%></p>
                  <p>Windows Sensitivity: <%=@player.winSens%> / 11</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i> Display Settings</h4>
                </div>
                <div class="panel-body">
                  <p>Reslution: <%=@player.resolution%></p>
                  <p>Aspect Ratio: <%=@player.aspectRatio%></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i> Hardware</h4>
                </div>
                <div class="panel-body">
                  <% if( @player.mouse != "" || nil) then %>
                    <p>Mouse: <%=@player.mouse%></p>
                  <% end%>
                  <% if( @player.monitor != "" || nil) then %>
                    <p>Monitor: <%=@player.monitor%></p>
                  <% end%>
                  <% if( @player.keyboard != ""  || nil ) then %>
                    <p>Keyboard: <%=@player.keyboard%></p>
                  <% end%>
                  <% if( @player.headset != "" || nil) then %>
                    <p>Headset: <%=@player.headset%></p>
                  <% end%>
                  <% if( @player.mousePad != "" || nil) then %>
                    <p>MousePad: <%=@player.mousePad%></p>
                  <% end%>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <hr>
  </div>

  <!-- View All -->
  <section class="no-padding" id="contact">
    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
              <!-- If player is in a team, return to team page, else return to teams listing-->
                <%@playerTeam = Team.find_by teamName: "#{@player.teamName}"%>
                <% if (@playerTeam !=nil) then %>
                  <h3 class="section-heading">View TEAM <%=(@player.teamName).upcase%>'s Roster.</h3>
                  <br></br>
                  <a href= "<%=team_path(@playerTeam.id)%>" class="btn-round-lg btn-xl">Discover More</a>
                <%else%>
                  <h3 class="section-heading">View Other Teams.</h3>
                  <br></br>
                  <a href= "<%=teams_path%>" class="btn-round-lg btn-xl">Discover</a>
                <%end%>
                <!-- <%= link_to 'Edit', edit_player_path(@player) %>  -->
            </div>
        </div>
    </aside>
  </section>

  <!-- Plugin JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/scrollreveal/scrollreveal.min.js"></script>
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Theme JavaScript -->
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/js/creative.min.js"></script>

</body>

<!-- <%= link_to 'Edit', edit_player_path(@player) %>  -->

<!--<%= link_to 'Back', players_path %>
-->